import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import Anthropic from '@anthropic-ai/sdk';
import OpenAI from 'openai';
import { fal } from '@fal-ai/client';
import { PrismaService } from '../../common/prisma.service';
import { StorageService } from '../../common/storage.service';
import { ContentSafetyService } from '../safety/content-safety.service';

interface CharacterDescription {
  faceShape: string;
  hairColor: string;
  hairStyle: string;
  eyeColor: string;
  skinTone: string;
  clothingStyle: string;
  distinguishingFeatures: string[];
  stylePrompt: string;
}

@Injectable()
export class CharacterEngineService {
  private readonly logger = new Logger(CharacterEngineService.name);
  private readonly openai: OpenAI;
  private readonly anthropic: Anthropic;

  constructor(
    private config: ConfigService,
    private prisma: PrismaService,
    private storage: StorageService,
    private safety: ContentSafetyService,
  ) {
    this.openai = new OpenAI({ apiKey: config.get('OPENAI_API_KEY') });
    this.anthropic = new Anthropic({
      apiKey: config.get<string>('ANTHROPIC_API_KEY'),
    });
    fal.config({ credentials: config.get<string>('FAL_API_KEY') });
  }

  async extractCharacterFromImage(
    childProfileId: string,
    imageBuffer: Buffer,
    imageExtension: string,
  ): Promise<string> {
    // Gate 5: Validate the uploaded photo before processing
    const mediaType = imageExtension === 'png' ? 'image/png' : 'image/jpeg';
    await this.safety.validateUploadedPhoto(
      imageBuffer.toString('base64'),
      mediaType as 'image/png' | 'image/jpeg',
    );

    // Store the reference image
    const storageKey = await this.storage.uploadCharacterReference(
      imageBuffer,
      childProfileId,
      imageExtension,
    );
    const imageUrl = await this.storage.getSignedUrl(storageKey);

    // Use GPT-4o Vision to analyze the child's appearance
    // (GPT-4o has the best structured vision output for physical feature extraction)
    const response = await this.openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: `You are an expert character designer for children's book illustrations. Analyze the child in the photo and create a detailed character description that can be used to maintain PERFECT consistency across 15+ illustrations generated by AI.

Your description must be so precise that an illustrator could draw the same character on every page without seeing the photo again. Focus on:
- Exact physical features (not approximate — specify "round face with soft chin" not just "round face")
- Hair specifics (color with undertones, length, texture, how it falls)
- Eye shape AND color with detail
- Skin tone (use specific descriptors, not vague terms)
- Body proportions appropriate for the age
- One or two signature features that make this character instantly recognizable

Do NOT describe clothing — that will vary by story. Respond with JSON only.`,
        },
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text: 'Analyze this child and create a character description sheet. Return JSON with: faceShape, hairColor, hairStyle, eyeColor, skinTone, clothingStyle (preferred style, not specific outfit), distinguishingFeatures (array), and stylePrompt (a single detailed paragraph describing the character for an AI illustrator to maintain consistency — this is the most important field, be extremely specific).',
            },
            {
              type: 'image_url',
              image_url: { url: imageUrl },
            },
          ],
        },
      ],
      response_format: { type: 'json_object' },
      max_tokens: 1000,
    });

    const description = JSON.parse(response.choices[0].message.content!) as CharacterDescription;

    // Generate a seed for reproducibility
    const seed = Math.floor(Math.random() * 2147483647);

    // Create character profile in database
    const profile = await this.prisma.characterProfile.create({
      data: {
        childProfileId,
        referenceImageUrl: this.storage.getPublicUrl(storageKey),
        faceShape: description.faceShape,
        hairColor: description.hairColor,
        hairStyle: description.hairStyle,
        eyeColor: description.eyeColor,
        skinTone: description.skinTone,
        clothingStyle: description.clothingStyle,
        distinguishingFeatures: description.distinguishingFeatures,
        stylePrompt: description.stylePrompt,
        seed,
      },
    });

    // Generate the canonical character reference illustration
    // This becomes the IP-Adapter anchor for all subsequent page illustrations
    await this.generateCharacterReferenceImage(profile.id, description, seed);

    this.logger.log(`Created character profile ${profile.id} for child ${childProfileId}`);
    return profile.id;
  }

  async createManualProfile(
    childProfileId: string,
    description: Partial<CharacterDescription>,
  ): Promise<string> {
    const child = await this.prisma.childProfile.findUnique({
      where: { id: childProfileId },
    });
    if (!child) throw new Error('Child profile not found');

    // Use Claude Opus 4.6 to generate a rich, detailed style prompt
    let stylePrompt = description.stylePrompt;
    if (!stylePrompt) {
      const storyModel = this.config.get<string>(
        'ANTHROPIC_STORY_MODEL',
        'claude-opus-4-6',
      );
      const response = await this.anthropic.messages.create({
        model: storyModel,
        max_tokens: 500,
        messages: [
          {
            role: 'user',
            content: `You are an expert children's book character designer. Create a detailed, precise character description that an AI illustrator can use to draw the SAME character consistently across 15+ pages.

Child: ${child.name}, age ${child.age}
Features provided:
- Face shape: ${description.faceShape || 'round (default for age)'}
- Hair: ${description.hairColor || 'brown'} ${description.hairStyle || 'short'}
- Eyes: ${description.eyeColor || 'brown'}
- Skin tone: ${description.skinTone || 'medium'}
- Clothing style: ${description.clothingStyle || 'casual, age-appropriate'}
- Distinguishing features: ${(description.distinguishingFeatures || []).join(', ') || 'none specified'}

Write a single detailed paragraph that an AI illustrator would use as a reference. Include exact physical proportions, feature shapes, and one or two signature elements that make this character instantly recognizable on every page. Be specific enough that every generated image will show the same child.`,
          },
        ],
      });
      stylePrompt =
        response.content[0].type === 'text'
          ? response.content[0].text
          : '';
    }

    const seed = Math.floor(Math.random() * 2147483647);

    const profile = await this.prisma.characterProfile.create({
      data: {
        childProfileId,
        faceShape: description.faceShape || null,
        hairColor: description.hairColor || null,
        hairStyle: description.hairStyle || null,
        eyeColor: description.eyeColor || null,
        skinTone: description.skinTone || null,
        clothingStyle: description.clothingStyle || null,
        distinguishingFeatures: description.distinguishingFeatures || [],
        stylePrompt,
        seed,
      },
    });

    // Generate the canonical reference image for IP-Adapter consistency
    const fullDescription: CharacterDescription = {
      faceShape: description.faceShape || 'round',
      hairColor: description.hairColor || 'brown',
      hairStyle: description.hairStyle || 'short',
      eyeColor: description.eyeColor || 'brown',
      skinTone: description.skinTone || 'medium',
      clothingStyle: description.clothingStyle || 'casual',
      distinguishingFeatures: description.distinguishingFeatures || [],
      stylePrompt: stylePrompt!,
    };

    await this.generateCharacterReferenceImage(profile.id, fullDescription, seed);

    this.logger.log(`Created manual character profile ${profile.id}`);
    return profile.id;
  }

  /**
   * Generate a canonical "hero pose" reference image of the character.
   * This image is stored and used as the IP-Adapter reference for every
   * subsequent page illustration, ensuring visual consistency across the book.
   */
  private async generateCharacterReferenceImage(
    profileId: string,
    description: CharacterDescription,
    seed: number,
  ): Promise<string> {
    const prompt = `Children's book character reference sheet. Single character standing in a neutral pose, front-facing, centered on a plain white background. Clean watercolor illustration style.

CHARACTER: ${description.stylePrompt}

The character should be:
- Standing upright in a friendly, welcoming pose
- Smiling warmly with clear facial features visible
- Wearing simple, colorful clothing appropriate for a child
- Well-lit with even lighting, no dramatic shadows
- Drawn in a warm, whimsical children's book watercolor style
- Proportions appropriate for a child character

IMPORTANT: Plain white background. No other characters. No complex scenery. This is a character reference sheet for maintaining consistency.`;

    const model = this.config.get<string>(
      'FAL_IMAGE_MODEL',
      'fal-ai/flux-pro/v1.1',
    );

    const result = await fal.subscribe(model, {
      input: {
        prompt,
        image_size: { width: 1024, height: 1024 },
        num_images: 1,
        seed,
        safety_tolerance: '2',
      },
    });

    const imageUrl = result.data.images[0].url;
    const response = await fetch(imageUrl);
    const imageBuffer = Buffer.from(await response.arrayBuffer());

    // Store the reference illustration
    const storageKey = await this.storage.uploadBookAsset(
      imageBuffer,
      `character-profiles/${profileId}`,
      'reference-illustration.png',
      'image/png',
    );

    // Update profile with the reference illustration URL
    await this.prisma.characterProfile.update({
      where: { id: profileId },
      data: {
        referenceIllustrationUrl: this.storage.getPublicUrl(storageKey),
        referenceIllustrationKey: storageKey,
      },
    });

    this.logger.log(`Generated character reference illustration for profile ${profileId}`);
    return storageKey;
  }

  /**
   * Retrieve the reference illustration buffer for IP-Adapter usage.
   */
  async getReferenceImageUrl(profileId: string): Promise<string | null> {
    const profile = await this.prisma.characterProfile.findUnique({
      where: { id: profileId },
    });

    if (!profile?.referenceIllustrationKey) return null;

    return this.storage.getSignedUrl(profile.referenceIllustrationKey);
  }
}
